### PR TITLE
Initial implementation

### PR DESCRIPTION
**Pull request by rlamacraft**
This is a bunch of java classes that implements the RDA spec (link in README) as well as JSON annotations to deserialise compliant objects into these classes.

Just thought, we're going to have move this to the rspace-os org so that dmptool-java-client to can reference this project.

### CODE REVIEW

**Comment by rlamacraft** [comment]
@mKowalski256 Do you have permission to transfer this repo to the rspace-os org?

**Review by mKowalski256 — APPROVED** [review]
Looks good. Yes, please move the repo to rspace-os org.

**Comment by rlamacraft** [comment]
> Looks good. Yes, please move the repo to rspace-os org.

I can't, I don't have permission

**Comment by mKowalski256** [comment]
ok, I just moved this repo to rspace-os, and made it public.

**Pull request merged**
